app = "book-damp-voice-8215"
primary_region = "yul"

[build]
  dockerfile = "Dockerfile"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/app/wwwroot"
  url_prefix = "/"
  
[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  