app = "book-damp-voice-8215"
primary_region = "yul"

[build]
  dockerfile = "Book.Server/Dockerfile"  # Default build for backend

[env]
  ASPNETCORE_URLS = "http://+:8080"  # Backend port
  PORT = "8080"  # Default process port

[http_service]
  internal_port = 8080  # Backend API
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  internal_port = 8080  # Backend API routing
  protocol = "tcp"
  [[services.ports]]
    port = 80  # Map 8080 to 80 externally
    handlers = ["http"]
  [[services.ports]]
    port = 443  # HTTPS
    handlers = ["tls", "http"]

[[statics]]
  guest_path = "/app/wwwroot"  # Frontend static files from Book.Server
  url_prefix = "/"  # Serve frontend at root

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  