app = "book-damp-voice-8215"
primary_region = "yul"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/dotnet-core"]
  [build.args]
    BUILD_DIR = "Book.Server"  # Set context to Book.Server/

[env]
  ASPNETCORE_URLS = "http://+:8080"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/app/wwwroot"
  url_prefix = "/"
  
[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  