# fly.toml app configuration file generated for book-damp-voice-8215 on 2025-04-03T15:54:44-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "book-damp-voice-8215"
primary_region = "yul"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/dotnet-core"]

[env]
  ASPNETCORE_ENVIRONMENT = "Production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  