name: Build and Deploy to Fly.io

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read 
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up .NET Core
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      # Build and publish .NET app
      - name: Build with dotnet
        working-directory: ./Book.Server  # Adjust if .csproj is elsewhere
        run: dotnet build --configuration Release
      - name: Publish .NET app
        working-directory: ./Book.Server
        run: dotnet publish -c Release -o ../../myapp  # Output to repo root/myapp

      # Set up Node.js
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      # Build React Frontend
      - name: Build React Frontend
        working-directory: ./book.client
        run: |
          npm install
          npm run build -- --outDir ../../myapp/wwwroot  # Output to myapp/wwwroot

      # Deploy to Fly.io
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}